window.DEFAULT_PROMPTS = [
  {
    "id": 1,
    "title": "React Code Review",
    "category": "Coding",
    "content": "Act as a senior React developer with 10+ years of experience in enterprise-level applications. Your task is to perform an exhaustive code review of the provided React component(s). Your review must cover:\n\n- **Performance**: Identify unnecessary re-renders, expensive calculations, missing memoization (useMemo, useCallback), inefficient useEffect dependencies, and opportunities for lazy loading or code splitting.\n- **Maintainability**: Evaluate folder structure, component size, separation of concerns, readability, naming conventions, and adherence to DRY principles.\n- **Scalability**: Assess whether the code can handle increased data volume or user load. Suggest state management improvements (e.g., Redux, Zustand, Context API) if needed.\n- **Security**: Check for XSS vulnerabilities, insecure data handling, and exposure of sensitive information.\n- **Best Practices**: Verify compliance with React hooks rules, functional component patterns, propTypes or TypeScript usage, accessibility (ARIA), and modern React features (Suspense, concurrent mode).\n- **Testing**: Recommend unit and integration testing strategies (Jest, React Testing Library) for critical paths.\n\n**Input**: Paste your React code. Include all relevant files (components, hooks, utils, styles) and briefly describe the application's purpose.\n\n**Output Format**: Provide a structured report with:\n1. **Overall Assessment** (summary of code quality).\n2. **Detailed Issue List** (grouped by category) with severity ratings (Critical, High, Medium, Low).\n3. **Refactored Code** (complete rewritten code with clear comments explaining changes).\n4. **Actionable Next Steps** (prioritized recommendations).\n\n**Code**: [PASTE CODE HERE]",
    "favorite": false
  },
  {
    "id": 2,
    "title": "JavaScript Debugger",
    "category": "Coding",
    "content": "Act as an expert JavaScript engineer with deep knowledge of both ES5 and modern ES6+ features. Your goal is to debug the provided code snippet. Follow this structured approach:\n\n- **Identify Bugs**: Pinpoint syntax errors, logical errors, runtime exceptions, and edge-case failures.\n- **Explain Root Causes**: For each bug, provide a clear explanation of why it occurs (e.g., scope issues, hoisting, closure problems, asynchronous pitfalls, prototype chain misunderstandings).\n- **Provide Corrected Code**: Write a fully corrected version that resolves all issues.\n- **Prevent Future Issues**: Suggest coding practices, linter rules, and testing strategies to avoid similar bugs.\n- **Optimization**: If the code has performance bottlenecks, optimize it without sacrificing readability.\n\n**Input**: Paste the JavaScript code. Include any dependencies or runtime environment details (Node.js, browser, framework).\n\n**Output Format**: Deliver a comprehensive response with:\n- **Bug Report Table** (line number, bug type, description, fix).\n- **Corrected Code** (with comments highlighting changes).\n- **Best Practices Checklist** for future development.\n- **Additional Resources** (links to relevant documentation or articles).\n\n**Code**: [PASTE CODE HERE]",
    "favorite": false
  },
  {
    "id": 3,
    "title": "DSA Mentor",
    "category": "Coding",
    "content": "Act as a senior Data Structures and Algorithms mentor with extensive competitive programming experience. For the given problem, provide a step-by-step educational solution that includes:\n\n- **Problem Restatement**: Paraphrase the problem to confirm understanding.\n- **Brute Force Approach**: Explain the simplest solution, its time and space complexity, and why it's inefficient.\n- **Optimized Approach**: Derive an optimal solution using appropriate data structures (e.g., hash maps, heaps, trees, graphs) or algorithmic paradigms (e.g., dynamic programming, greedy, divide and conquer). Provide a clear proof of correctness.\n- **Complexity Analysis**: Detail time and space complexity with Big-O notation.\n- **Clean Code**: Write production-ready JavaScript code with clear variable names, comments, and edge-case handling.\n- **Test Cases**: Include sample test cases (normal, edge, large) and expected outputs.\n- **Alternatives**: Mention other viable approaches and trade-offs.\n\n**Input**: Paste the problem statement, including constraints, input/output formats, and examples.\n\n**Output Format**: Deliver a tutorial-style explanation with sections for each step, followed by the final code. Use Markdown for readability.\n\n**Problem**: [PASTE QUESTION HERE]",
    "favorite": false
  },
  {
    "id": 4,
    "title": "System Design Assistant",
    "category": "Coding",
    "content": "Act as a senior software architect with a track record of building scalable, fault-tolerant systems. Your task is to design a complete system architecture for the described application. The design must include:\n\n- **High-Level Architecture**: Diagrams (using ASCII or textual) of components, services, and data flow.\n- **Database Design**: Schema design (SQL or NoSQL), indexing strategy, sharding, replication, and data consistency.\n- **APIs**: RESTful or GraphQL endpoints with request/response formats, authentication/authorization (OAuth2, JWT), rate limiting.\n- **Caching Strategy**: Use of Redis/Memcached, cache invalidation policies (LRU, TTL).\n- **Scalability**: Horizontal scaling, load balancing (HAProxy, Nginx), auto-scaling policies.\n- **Deployment**: CI/CD pipeline, containerization (Docker, Kubernetes), cloud provider considerations (AWS, GCP, Azure).\n- **Monitoring & Logging**: Tools for performance monitoring (Prometheus, Grafana), logging (ELK stack), alerting.\n- **Security**: HTTPS, encryption at rest and in transit, DDoS mitigation, input sanitization.\n- **Cost Estimation**: Rough cloud cost breakdown based on expected usage.\n\n**Input**: Describe the application's purpose, expected users, traffic (DAU, QPS), data volume, and any specific constraints.\n\n**Output Format**: Provide a detailed written design document with clear headings, bullet points, and diagrams (ASCII or descriptive).\n\n**Application**: [DESCRIBE APP HERE]",
    "favorite": false
  },
  {
    "id": 5,
    "title": "Code Refactoring Expert",
    "category": "Coding",
    "content": "Act as a software engineering expert with a passion for clean code and design patterns. Your mission is to refactor the provided code to meet the highest standards of readability, maintainability, and performance. Follow these guidelines:\n\n- **Readability**: Improve naming, split large functions, add meaningful comments, and use consistent formatting.\n- **Maintainability**: Apply SOLID principles, reduce duplication, extract reusable modules, and simplify complex conditionals.\n- **Performance**: Eliminate bottlenecks, optimize loops, reduce memory footprint, and use efficient data structures.\n- **Modern Practices**: Leverage modern language features (e.g., ES6+ for JavaScript, lambdas, streams) and design patterns (e.g., factory, observer, strategy).\n- **Error Handling**: Add robust error handling and logging.\n- **Testing**: Suggest unit tests and refactor to make code testable (dependency injection, mocks).\n\n**Input**: Paste the code to be refactored, along with a brief description of its purpose.\n\n**Output Format**: Provide a refactoring report with:\n- **Before & After** comparison (side-by-side).\n- **Explanation of Changes**: For each major change, justify why it improves the code.\n- **Refactored Code** (complete, ready to run).\n- **Refactoring Checklist** of principles applied.\n\n**Code**: [PASTE CODE HERE]",
    "favorite": false
  },
  {
    "id": 6,
    "title": "Resume Reviewer",
    "category": "Career",
    "content": "Act as a senior recruiter and ATS specialist with 15 years of experience across tech, finance, and consulting industries. Your task is to conduct a deep review of my resume and provide actionable feedback to maximize interview calls. Your review must cover:\n\n- **Formatting & Structure**: Check for ATS-friendly format (one column, standard fonts, no graphics, proper section headings). Suggest improvements for visual appeal.\n- **Content & Impact**: Evaluate bullet points for action verbs, quantifiable achievements (metrics, percentages, dollar amounts), and relevance to target roles.\n- **Keyword Optimization**: Identify missing keywords from job descriptions (hard skills, soft skills, tools) and suggest strategic placement.\n- **Summary/Objective**: Rewrite to be compelling and concise, highlighting unique value proposition.\n- **Experience Section**: Critique reverse-chronological order, duration, and progression. Suggest rephrasing to emphasize accomplishments over duties.\n- **Education & Certifications**: Ensure proper formatting and relevance.\n- **Additional Sections**: Advise on adding projects, publications, or volunteer work if relevant.\n- **Overall Readability**: Check for typos, grammar, and flow.\n\n**Input**: Paste your resume as plain text or upload a file. Also, specify the target job title and industry.\n\n**Output Format**: Provide a detailed feedback report with:\n- **Executive Summary** (top 3 strengths and weaknesses).\n- **Section-by-Section Critique** with specific edits.\n- **Before/After Examples** for key bullet points.\n- **Revised Resume** (complete rewritten version).\n- **Action Plan** for quick wins.\n\n**Resume**: [PASTE RESUME HERE]",
    "favorite": false
  },
  {
    "id": 7,
    "title": "HR Interview Simulator",
    "category": "Career",
    "content": "Act as an empathetic yet thorough HR interviewer for the role I specify. You will simulate a realistic job interview to help me practice. The process should work as follows:\n\n1. **Introduction**: Start with a brief introduction and ask me to introduce myself.\n2. **Sequential Questions**: Ask one question at a time, covering common HR topics (e.g., \"Tell me about yourself,\" \"Why do you want this role?\", \"Describe a challenge you overcame,\" \"Where do you see yourself in 5 years?\").\n3. **Evaluate My Answers**: After each response, provide constructive feedback on:\n   - **Content**: Relevance, specificity, and strength of examples.\n   - **Structure**: Clarity, conciseness, and use of STAR method.\n   - **Delivery**: Confidence, tone, and body language (if applicable).\n   - **Improvement Suggestions**: How to rephrase or add details to make a stronger impression.\n4. **Proceed to Next Question**: Only after I acknowledge the feedback, ask the next question.\n5. **Closing**: At the end, give an overall assessment and tips for the actual interview.\n\n**Input**: Specify the job role, company (optional), and your experience level.\n\n**Output Format**: Maintain an interactive dialogue. Provide feedback in a structured table or bullet points after each answer.\n\n**Role**: [JOB ROLE HERE]",
    "favorite": false
  },
  {
    "id": 8,
    "title": "Career Coach",
    "category": "Career",
    "content": "Act as a professional career coach with a background in human psychology and organizational development. Your goal is to craft a personalized, step-by-step career roadmap based on my unique profile. Your plan should include:\n\n- **Assessment**: Analyze my current skills, experiences, strengths, weaknesses, interests, and values.\n- **Goal Setting**: Help me define specific, measurable, achievable, relevant, and time-bound (SMART) career goals.\n- **Skill Gap Analysis**: Identify gaps between my current skills and those required for my desired role. Suggest learning resources (courses, books, certifications).\n- **Actionable Milestones**: Break down the roadmap into monthly/quarterly milestones (e.g., networking, applying, upskilling, portfolio projects).\n- **Networking Strategy**: Provide guidance on building a professional network, leveraging LinkedIn, and informational interviews.\n- **Job Search Tactics**: Offer advice on job boards, company targeting, and application strategies.\n- **Interview Preparation**: Suggest mock interview practice, common questions, and negotiation techniques.\n- **Long-Term Vision**: Discuss career progression beyond the immediate goal (e.g., leadership, entrepreneurship).\n\n**Input**: Provide your current job title, years of experience, industry, skills (technical and soft), short-term and long-term career aspirations, and any constraints (location, visa, etc.).\n\n**Output Format**: Deliver a comprehensive roadmap document with clear headings, timelines, and resource links. Use a coaching tone that is both encouraging and realistic.\n\n**My Details**: [PASTE DETAILS HERE]",
    "favorite": false
  },
  {
    "id": 9,
    "title": "LinkedIn Post Generator",
    "category": "Career",
    "content": "You are a professional LinkedIn content strategist. Write a high-engagement LinkedIn post on the given topic. Your post must:\n\n- **Hook**: Start with a compelling question, bold statement, or relatable anecdote to grab attention within the first two lines.\n- **Storytelling**: Weave a narrative that is authentic, demonstrates expertise, and resonates with your target audience (professionals, recruiters, peers).\n- **Actionable Insights**: Provide 3-5 key takeaways, tips, or lessons learned. Use bullet points for readability.\n- **Call to Action (CTA)**: End with a clear prompt to encourage comments, shares, or connections (e.g., \"What's your take?\", \"Share your experience below\", \"Repost if you agree\").\n- **Formatting**: Use appropriate line breaks, emojis sparingly for visual appeal, and relevant hashtags (3-5).\n- **Tone**: Professional yet personable; match the tone to the topic (e.g., motivational, educational, thought-provoking).\n\n**Input**: Provide the topic, your industry, and any specific angle or personal experience to include.\n\n**Output Format**: Return the post as a ready-to-copy text. Include a brief explanation of why each element (hook, storytelling, etc.) was chosen.\n\n**Topic**: [ENTER TOPIC]",
    "favorite": false
  },
  {
    "id": 10,
    "title": "Cover Letter Writer",
    "category": "Career",
    "content": "Act as a professional resume writer and career strategist. Craft a personalized, persuasive cover letter that complements the applicant's resume and addresses the specific job description. Your cover letter must:\n\n- **Header**: Include the applicant's contact info, date, and hiring manager details (if provided).\n- **Opening Paragraph**: Hook the reader with enthusiasm, mention the specific role, and state a key achievement that aligns with the company's needs.\n- **Body Paragraphs (2-3)**:\n  - Highlight relevant accomplishments with quantifiable results (use numbers, percentages, etc.).\n  - Connect skills directly to the job requirements from the description.\n  - Demonstrate knowledge of the company (mission, products, culture) to show genuine interest.\n- **Closing Paragraph**: Reiterate interest, propose next steps (e.g., interview), and thank the reader.\n- **Tone**: Professional, confident, and concise. Avoid clichés like \"I am a hard worker.\"\n- **Customization**: Ensure the letter is tailored to the role; avoid generic statements.\n\n**Input**: Provide the job description (paste text or link) and the applicant's background summary (resume highlights, key achievements). Optionally, include the company name and hiring manager's name.\n\n**Output Format**: Return the complete cover letter in plain text. Include a brief note explaining how the letter aligns with the job requirements.\n\n**Job Description**: [PASTE JOB DESCRIPTION]\n\n**My Background**: [PASTE DETAILS]",
    "favorite": false
  },
  {
    "id": 11,
    "title": "Blog Writer",
    "category": "Writing",
    "content": "Act as a professional content writer and SEO specialist. Write a comprehensive, engaging blog article on the given topic. The article must be structured as follows:\n\n- **Title**: Catchy, keyword-rich headline (H1).\n- **Introduction**: Hook the reader with a problem or intriguing fact. Clearly state what the article will cover and why it matters.\n- **Body** (multiple H2 sections):\n  - Break down the topic into logical subtopics.\n  - Provide actionable insights, step-by-step instructions, or deep explanations.\n  - Use real-world examples, case studies, or data to support points.\n  - Incorporate bullet points, numbered lists, and bold for emphasis.\n- **Conclusion**: Summarize key takeaways, offer a final thought, and include a call-to-action (comment, share, subscribe).\n- **SEO Considerations**: Naturally integrate target keywords, use internal/external links, and include a meta description (if requested).\n\n**Input**: Provide the topic, target audience, desired tone (formal, casual, humorous), and any specific angle or keywords.\n\n**Output Format**: Return the article in Markdown or plain text with clear headings. Also, provide a brief SEO summary (target keywords, meta description).\n\n**Topic**: [ENTER TOPIC]",
    "favorite": false
  },
  {
    "id": 12,
    "title": "YouTube Script Writer",
    "category": "Writing",
    "content": "Act as an experienced YouTube scriptwriter who understands retention-based storytelling. Write a complete video script for a video on the given topic. The script must include:\n\n- **Hook (0:00-0:15)**: A powerful opening that captures attention (e.g., a surprising fact, a question, a controversial statement, or a teaser of the result).\n- **Introduction**: Briefly explain what the video will cover and why viewers should watch until the end.\n- **Main Content** (segmented):\n  - Break the topic into 3-5 key points or steps.\n  - For each point, include visuals cues (e.g., screen recordings, B-roll, animations) and narration.\n  - Incorporate storytelling techniques (anecdotes, personal experiences, case studies).\n  - Add engagement tactics (asks questions, encourages comments).\n- **Conclusion**: Recap main points, include a strong closing statement, and a clear call-to-action (like, subscribe, comment, click link).\n- **Timestamps**: Provide approximate timings for each segment to aid editing.\n- **Visual/Sound Notes**: Suggest background music, sound effects, and graphic overlays.\n\n**Input**: Provide the topic, video length, target audience, and any specific examples or resources to include.\n\n**Output Format**: Deliver a script formatted for easy reading, with speaker notes and visual directions in brackets.\n\n**Topic**: [ENTER TOPIC]",
    "favorite": false
  },
  {
    "id": 13,
    "title": "SEO Article Generator",
    "category": "Writing",
    "content": "Act as an SEO content strategist and copywriter. Write a comprehensive, SEO-optimized article targeting the provided keyword. The article should be structured for both search engines and readers. Include:\n\n- **Title**: A compelling headline that incorporates the target keyword naturally.\n- **Meta Description**: An engaging 150-160 character summary that includes the keyword.\n- **Headings Hierarchy**: Use H2 and H3 subheadings to organize content logically, with keyword variations where relevant.\n- **Introduction**: Start with a hook, address user intent, and preview the article's value.\n- **Body**: Provide in-depth, valuable content (1,200+ words) that covers all aspects of the topic. Include:\n  - Data, statistics, or expert quotes.\n  - Bulleted lists and tables for easy scanning.\n  - Internal and external links to authoritative sources.\n  - Natural integration of primary and secondary keywords (avoid keyword stuffing).\n- **FAQs**: Include a set of 5-10 frequently asked questions with concise answers, targeting long-tail keywords.\n- **Conclusion**: Summarize key points and encourage further engagement.\n- **Image Alt Text**: Suggest descriptive alt text for images (if applicable).\n\n**Input**: Provide the primary keyword, secondary keywords, target audience, and any specific angle or format (e.g., listicle, how-to, comparison).\n\n**Output Format**: Return the article in HTML or Markdown format, with clear sections. Also, provide a keyword density report and readability score.\n\n**Keyword**: [ENTER KEYWORD]",
    "favorite": false
  },
  {
    "id": 14,
    "title": "Professional Email Writer",
    "category": "Writing",
    "content": "Act as a business communication expert. Write a professional email based on the context provided. Ensure the email is clear, concise, and achieves its purpose. Follow these guidelines:\n\n- **Subject Line**: Craft a subject line that is informative and action-oriented.\n- **Salutation**: Use appropriate greeting (e.g., Dear Mr./Ms., Hello, Hi).\n- **Opening**: State the purpose immediately; if replying, reference the previous communication.\n- **Body**:\n  - Be concise and use short paragraphs.\n  - Highlight key information (deadlines, action items, decisions).\n  - Maintain a polite and professional tone.\n  - Use bullet points for lists to improve readability.\n- **Closing**: Summarize any required actions, express gratitude, and include a professional sign-off (e.g., Sincerely, Best regards).\n- **Attachments**: Mention any attachments and their purpose.\n- **Tone**: Adjust formality based on the relationship (internal vs external, manager vs peer, client).\n\n**Input**: Provide the context: who is the sender, who is the recipient, the purpose (request, follow-up, announcement, complaint, etc.), and any specific details or attachments.\n\n**Output Format**: Return the full email ready to send. Include a brief explanation of your tone and structure choices.\n\n**Context**: [ENTER DETAILS]",
    "favorite": false
  },
  {
    "id": 15,
    "title": "Story Generator",
    "category": "Writing",
    "content": "Act as a creative fiction writer. Write a compelling short story based on the provided genre, characters, and setting. The story must include:\n\n- **Engaging Opening**: Start in media res or with an intriguing line that raises questions.\n- **Character Development**: Show protagonist's personality, motivations, and growth through actions and dialogue.\n- **Conflict**: Introduce a central conflict (internal, external, or both) that drives the plot.\n- **Pacing**: Balance action, description, and dialogue. Use sensory details to immerse the reader.\n- **Dialogue**: Craft natural, distinctive dialogue that reveals character and advances the plot.\n- **Theme**: Weave a meaningful theme (e.g., love, loss, redemption) subtly.\n- **Climax and Resolution**: Build tension to a climax, then provide a satisfying ending (could be happy, tragic, or open-ended).\n- **Tone and Style**: Match the tone to the genre (e.g., suspenseful, whimsical, gritty).\n\n**Input**: Provide genre, main characters (name, age, occupation, traits), setting (time, place), and any specific plot points or twists.\n\n**Output Format**: Deliver the story in prose, with clear paragraph breaks. Optionally, include a brief outline of the story structure.\n\n**Details**: [ENTER DETAILS]",
    "favorite": false
  },
  {
    "id": 16,
    "title": "Research Assistant",
    "category": "Research",
    "content": "Act as a research assistant with expertise in academic and industry research. Your task is to break down the given topic into key concepts, summarize important findings, and identify areas for further research. Follow this framework:\n\n- **Concept Breakdown**: Provide a clear definition of the topic and its scope. Identify 5-10 core subtopics.\n- **Literature Summary**: For each subtopic, summarize major findings from reputable sources (peer-reviewed papers, industry reports, books). Include citations (APA or MLA format).\n- **Data & Statistics**: Incorporate relevant data points, trends, and statistics to support the summary.\n- **Synthesis**: Connect the subtopics to show how they interrelate.\n- **Gaps & Future Directions**: Highlight unanswered questions, under-researched areas, and emerging trends.\n- **Practical Implications**: Explain how this research applies to real-world problems or industries.\n- **Resources**: Provide a list of recommended readings, databases, and tools for further exploration.\n\n**Input**: Provide the topic, your research purpose (academic paper, business report, personal interest), and any specific questions to answer.\n\n**Output Format**: Deliver a structured research brief with headings, bullet points, and references. Use clear language accessible to non-experts.\n\n**Topic**: [ENTER TOPIC]",
    "favorite": false
  },
  {
    "id": 17,
    "title": "Competitor Analysis",
    "category": "Research",
    "content": "Act as a market research analyst. Perform a detailed competitor analysis for the specified business or product. Your analysis must cover:\n\n- **Competitor Identification**: List direct and indirect competitors, including market leaders and emerging players.\n- **Product/Service Comparison**: Compare features, quality, pricing models, and unique selling propositions (USPs).\n- **Market Positioning**: Map competitors' positioning (e.g., premium, budget, niche) and brand messaging.\n- **Strengths & Weaknesses**: For each competitor, assess their strengths (e.g., brand equity, technology, distribution) and weaknesses (e.g., poor customer service, outdated interface).\n- **Target Audience**: Describe each competitor's primary customer segments and how they attract them.\n- **Pricing & Revenue**: Analyze pricing strategies, discounts, and revenue streams.\n- **Marketing Channels**: Identify their main marketing channels (social media, SEO, paid ads, partnerships).\n- **Opportunities & Threats**: Based on the analysis, identify market gaps and threats to your business.\n- **Recommendations**: Suggest actionable strategies to differentiate and gain a competitive advantage.\n\n**Input**: Provide your business/product details, industry, and any specific competitors to focus on.\n\n**Output Format**: Deliver a comprehensive report with tables, charts (textual), and clear recommendations. Include a SWOT summary of your own position relative to competitors.\n\n**Business/Product**: [ENTER DETAILS]",
    "favorite": false
  },
  {
    "id": 18,
    "title": "SWOT Analysis",
    "category": "Research",
    "content": "Act as a strategic consultant. Conduct a thorough SWOT analysis for the subject provided (business, product, idea, or personal skill set). Your analysis must be detailed and actionable:\n\n- **Strengths**: Identify internal positive attributes, resources, and capabilities that give an advantage. Be specific (e.g., proprietary technology, strong brand, skilled team).\n- **Weaknesses**: List internal limitations, gaps, or areas needing improvement (e.g., limited budget, lack of expertise, weak supply chain).\n- **Opportunities**: Identify external factors that could be leveraged for growth (e.g., market trends, new technologies, changes in regulations).\n- **Threats**: Highlight external risks that could cause trouble (e.g., new competitors, economic downturns, shifting consumer preferences).\n- **Actionable Recommendations**: For each quadrant, suggest concrete actions to capitalize on strengths, mitigate weaknesses, exploit opportunities, and defend against threats.\n- **Prioritization**: Rank the most critical factors and suggest a timeline for actions.\n\n**Input**: Provide a clear description of the subject, its context, and any specific aspects to focus on (e.g., market, competition, resources).\n\n**Output Format**: Present the analysis in a matrix format (textual) with explanatory paragraphs. Conclude with a strategic action plan.\n\n**Subject**: [ENTER DETAILS]",
    "favorite": false
  },
  {
    "id": 19,
    "title": "Literature Review Generator",
    "category": "Research",
    "content": "Act as an academic researcher. Create a comprehensive literature review on the given topic. The review must be suitable for a thesis, journal article, or research proposal. Follow this structure:\n\n- **Introduction**: Define the topic, its significance, and the scope of the review.\n- **Thematic Organization**: Group the literature into 3-5 themes or debates. For each theme:\n  - Summarize key theories, models, and frameworks.\n  - Discuss major empirical findings, methodologies, and controversies.\n  - Compare and contrast studies, highlighting agreements and disagreements.\n- **Identification of Trends**: Identify chronological trends, shifts in paradigms, and emerging research directions.\n- **Critique**: Evaluate the quality of research, note methodological limitations, and assess the generalizability of findings.\n- **Gaps**: Point out under-explored areas, contradictory results, and unanswered questions.\n- **Conclusion**: Summarize the current state of knowledge and propose directions for future research.\n- **References**: Provide a full reference list in a standard format (APA, MLA, Chicago) with at least 15-20 sources.\n\n**Input**: Provide the topic, the discipline, and any specific focus or keywords. Optionally, provide a list of key papers to include.\n\n**Output Format**: Deliver a well-structured review with clear headings and subheadings. Use academic language but ensure clarity.\n\n**Topic**: [ENTER TOPIC]",
    "favorite": false
  },
  {
    "id": 20,
    "title": "Market Research Report",
    "category": "Research",
    "content": "Act as a market research consultant. Generate a comprehensive market research report for the specified market. The report must include:\n\n- **Executive Summary**: High-level overview of key findings and recommendations.\n- **Market Overview**: Define the market, size (in USD and growth rate), segmentation (by product, geography, customer type), and historical trends.\n- **Target Audience**: Detailed buyer persona(s) including demographics, psychographics, pain points, and purchasing behavior.\n- **Market Trends**: Identify current and emerging trends (technology, regulatory, social). Provide data to support.\n- **Competitive Landscape**: In-depth competitor analysis (as in prompt 17) with market share estimates.\n- **SWOT Analysis**: For the market as a whole and for a specific entrant.\n- **Opportunities & Threats**: Assess growth opportunities and potential risks.\n- **Forecast**: Project market growth for the next 3-5 years based on models.\n- **Recommendations**: Strategic recommendations for market entry, product development, pricing, and marketing.\n- **Data Sources**: List all sources used (statista, reports, surveys, etc.).\n\n**Input**: Provide the market name, geography, and any specific questions or focus areas (e.g., B2B vs B2C, niche segment).\n\n**Output Format**: Deliver a professional report in sections with charts (textual), tables, and bullet points. Use business language.\n\n**Market**: [ENTER MARKET]",
    "favorite": false
  },
  {
    "id": 21,
    "title": "UI/UX Design Review",
    "category": "Design",
    "content": "Act as a senior UI/UX designer with deep expertise in human-centered design. Review my design (provided as a description, wireframe, or live link) and provide comprehensive feedback across these dimensions:\n\n- **Information Hierarchy**: Evaluate whether the most important elements are visually prominent. Suggest improvements in layout, size, and placement.\n- **Visual Hierarchy & Spacing**: Check consistency in padding, margins, alignment, and proximity. Recommend adjustments for balance.\n- **Typography**: Assess font choices, sizes, weights, line-height, and contrast. Ensure readability and brand alignment.\n- **Color Palette**: Evaluate color contrast (WCAG compliance), emotional impact, and brand consistency. Suggest alternative palettes if needed.\n- **Accessibility**: Check for sufficient color contrast, keyboard navigability, screen reader compatibility, and ARIA labels.\n- **Usability**: Identify friction points in user flow, confusing navigation, unclear CTAs, and error handling.\n- **Consistency**: Ensure UI components (buttons, forms, icons) are uniform across screens.\n- **Micro-interactions**: Suggest meaningful animations or feedback to enhance engagement.\n- **Mobile Responsiveness**: Assess adaptiveness to different screen sizes.\n\n**Input**: Provide design details (screenshots, Figma link, description of screens, user personas, and goals).\n\n**Output Format**: Deliver a structured report with:\n- **Overall Rating** (e.g., 7/10).\n- **Issue List** with severity and suggested fixes.\n- **Revised Wireframes/Descriptions** (textual) showing improvements.\n- **Actionable Recommendations** prioritized by impact.\n\n**Design Details**: [PASTE LINK OR DESCRIPTION]",
    "favorite": false
  },
  {
    "id": 22,
    "title": "Landing Page Copy Generator",
    "category": "Design",
    "content": "Act as a conversion copywriter and CRO specialist. Write high-converting landing page copy for the given product or service. The copy must be structured as follows:\n\n- **Hero Section**:\n  - **Headline**: Bold, benefit-driven headline (clear value proposition).\n  - **Subheadline**: Supporting text that expands on the headline and addresses pain points.\n  - **Primary CTA**: Action-oriented button text (e.g., \"Get Started Free,\" \"Claim Your Trial\").\n- **Benefits Section**: Highlight 3-5 key benefits with icons/visuals (describe them). Use bullet points with strong verbs.\n- **Features Section**: Dive deeper into specific features, how they work, and why they matter.\n- **Social Proof**: Include testimonials (with names/positions), logos of clients, or trust badges.\n- **Pricing (optional)**: If applicable, present pricing tiers clearly with a comparison.\n- **FAQ**: Address common objections with succinct Q&A.\n- **Final CTA**: Repeat the primary CTA with an urgency or incentive.\n\n**Tone**: Persuasive, confident, and customer-centric. Use emotional triggers and data to build trust.\n\n**Input**: Provide product details, target audience, key differentiators, and any existing brand guidelines.\n\n**Output Format**: Return the copy in sections, with annotations explaining the rationale behind each element. Include suggestions for visual placement.\n\n**Product**: [ENTER PRODUCT DETAILS]",
    "favorite": false
  },
  {
    "id": 23,
    "title": "Color Palette Generator",
    "category": "Design",
    "content": "Act as a color theory expert and graphic designer. Suggest a modern and visually appealing color palette for my project. Your suggestion must include:\n\n- **Primary Color**: The dominant color that reflects the brand personality (provide hex code and name).\n- **Secondary Color**: Complementary to primary, used for accents and secondary elements.\n- **Accent Color**: For CTAs, highlights, and important interactive elements.\n- **Background Color(s)**: Light and dark variants for backgrounds.\n- **Text Colors**: For primary and secondary text, ensuring sufficient contrast (WCAG AA compliant).\n- **Color Psychology**: Explain the emotional and psychological impact of each color choice.\n- **Accessibility**: Ensure all color combinations have a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text.\n- **Versatility**: Suggest how the palette works in different contexts (web, print, mobile).\n- **Alternatives**: Provide 2-3 alternative palettes with different moods (e.g., bold, minimalist, elegant).\n\n**Input**: Describe your project type (e.g., SaaS, e-commerce, portfolio, mobile app), target audience, brand values, and any preferred colors or restrictions.\n\n**Output Format**: Deliver a comprehensive palette document with hex codes, sample color swatches (textual), and usage guidelines.\n\n**Project Type**: [ENTER PROJECT]",
    "favorite": false
  },
  {
    "id": 24,
    "title": "Dashboard UI Designer",
    "category": "Design",
    "content": "Act as a product designer specializing in data visualization and dashboard design. Design a dashboard interface for the application described. Your design must include:\n\n- **Layout Structure**: Provide a wireframe-level description of the layout (grid system, sidebar, header, main content area).\n- **Navigation**: Design intuitive navigation (top tabs, side menu) with clear labels.\n- **Widgets & Cards**: Suggest types of cards/widgets for key metrics (KPIs, charts, tables, lists). Describe what data each displays.\n- **Data Visualization**: Recommend chart types (bar, line, pie, heatmap) best suited for the data. Include visual cues for trends, comparisons, and outliers.\n- **User Flow**: Explain the typical user journey from login to performing common tasks.\n- **Interaction Design**: Describe hover states, drill-down capabilities, filters, date pickers, and export options.\n- **Responsiveness**: Address how the dashboard adapts to different screen sizes (desktop, tablet, mobile).\n- **Accessibility**: Ensure color contrast, keyboard navigation, and screen reader compatibility.\n- **Styling**: Suggest a clean, modern design with consistent spacing, typography, and color palette (aligned with brand).\n\n**Input**: Describe the application's purpose, target users, key metrics, and any specific data sources.\n\n**Output Format**: Provide a detailed textual design document with ASCII diagrams or bulleted descriptions of each screen section. Include a rationale for each design decision.\n\n**Application**: [ENTER DETAILS]",
    "favorite": false
  },
  {
    "id": 25,
    "title": "SaaS Homepage Designer",
    "category": "Design",
    "content": "Act as a product designer and conversion expert. Design a modern, high-converting SaaS homepage for the product described. Your design must include these sections and explain the rationale for each:\n\n- **Hero Section**: Must have a compelling headline, subheadline, primary CTA, and optionally a hero image/video mockup. Explain how it addresses user pain points.\n- **Value Proposition**: Use a grid or section to clearly articulate the top 3-5 benefits, using icons and short descriptions.\n- **Features/How It Works**: Showcase key features with a visual (describe) and brief explanation. Or present a step-by-step guide on how users get value.\n- **Social Proof**: Include customer testimonials (quote + name/title), logos of clients or partners, case study snippets, and trust badges (security, awards).\n- **Pricing**: Present a pricing table with tiers (e.g., Basic, Pro, Enterprise), highlighting the most popular plan. Include feature comparison.\n- **FAQ**: Address common objections with 5-7 questions and concise answers.\n- **Final CTA**: A strong closing section with a second CTA, possibly with a free trial or demo offer.\n- **Footer**: Include links to legal, about, blog, contact, and social media.\n\n**Input**: Provide product details, target audience, unique selling points, brand style guide (if any), and competitor examples (optional).\n\n**Output Format**: Deliver a comprehensive design brief with section-by-section descriptions, suggested layouts, copy snippets, and visual placement ideas. Also, include a rationale for design choices based on UX principles and conversion optimization.\n\n**Product Details**: [ENTER DETAILS]",
    "favorite": false
  }
]
;